# Typus Roles Configuration File
#
# Use the README file as a reference to customize settings.

admin:
  Authorization: create, read, update, delete
  Checkin: create, read, update, delete
  Location: create, read, update, delete
  Status: create, read, update, delete
  User: create, read, update, delete
