development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: qrcode_game_dev
  pool: 5
  username: root
  password: 
  host: localhost
    
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: qrgame
  pool: 5
  username: qrgame
  password: qr2011!8bit
  host: localhost